//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasteOfTheWorld.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneProjectEntities : DbContext
    {
        public CapstoneProjectEntities()
            : base("name=CapstoneProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
    }
}
