//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasteOfTheWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Recipe_Id { get; set; }
        public string Name_of_Dish { get; set; }
        public string Dish_Description { get; set; }
        public string Image_URL { get; set; }
        public string Ingredients { get; set; }
        public string Directions { get; set; }
        public string Chef_Id { get; set; }
        public int Country_Id { get; set; }
    
        public virtual Chef Chef { get; set; }
        public virtual Country Country { get; set; }
    }
}
